### ISSUE TITLE
Question about training

### ISSUE THREAD

**Issue by ylfzr** [dsanno/chainer-cf-nade#2]
Very beautiful implementation, but I still have a little question.  
In your trainer, I see you used  "weight", which is the number of items this user rated divided by the number of ratings used for validate of the this user.  Why we need this "weight" to modify the softmax loss?  I didn't see this in the original paper...

**Comment by dsanno** [comment]
Hi ylfzr

The "weight" is used in implementation by the author.

see
https://github.com/Ian09/CF-NADE/blob/master/learner_masked_ordinalcost_directly_itembased_newsoftmax_timing.py#L60
In `rating_cost`,  `D` indicates the number of ratings the user rated and `d` indicates the number of ratings for training (so `D - d` indicates the number of ratings for validation of the user)

**Comment by ylfzr** [comment]
Hi dsanno:

Thank you for your reply. I saw that in the original implementation. It seems that this weighted mask really do something. When I use a all one weight, the overall rmse goes up to 0.839 from 0.834
